// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ShopEgypt.Domain.Entities;

[Table("Cart")]
public partial class Cart
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(450)]
    public string ApplicationUserId { get; set; }

    public DateTime CreatedAt { get; set; }

    [ForeignKey("ApplicationUserId")]
    [InverseProperty("Carts")]
    public virtual ApplicationUser ApplicationUser { get; set; }

    [InverseProperty("Cart")]
    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();
}
