// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ShopEgypt.Domain.Entities;

[Table("Order")]
public partial class Order
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(450)]
    public string ApplicationUserId { get; set; }

    public DateTime OrderDate { get; set; }

    [Required]
    [StringLength(50)]
    public string Status { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal TotalAmount { get; set; }

    [StringLength(255)]
    public string Street { get; set; }

    [StringLength(100)]
    public string City { get; set; }

    [StringLength(100)]
    public string Governorate { get; set; }

    [StringLength(20)]
    public string PostalCode { get; set; }

    [ForeignKey("ApplicationUserId")]
    [InverseProperty("Orders")]
    public virtual ApplicationUser ApplicationUser { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    [InverseProperty("Order")]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}
