// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ShopEgypt.Domain.Entities;

[Table("Review")]
public partial class Review
{
    [Key]
    public int Id { get; set; }

    public int ProductId { get; set; }

    [Required]
    [StringLength(450)]
    public string ApplicationUserId { get; set; }

    public int Rating { get; set; }

    public string Comment { get; set; }

    public DateTime CreatedAt { get; set; }

    [ForeignKey("ApplicationUserId")]
    [InverseProperty("Reviews")]
    public virtual ApplicationUser ApplicationUser { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("Reviews")]
    public virtual Product Product { get; set; }
}
