// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ShopEgypt.Domain.Entities;

[Table("WishlistItems")]
public partial class WishlistItem
{
    [Key]
    public int Id { get; set; }

    [Required]
    public int WishlistID {get; set;}

    [ForeignKey("WishlistID")]
    public Wishlist? Wishlist { get; set; }

    [Required]
    public int ProductId { get; set; }


    [ForeignKey("ProductId")]
    [InverseProperty("WishlistItems")]
    public virtual Product? Product { get; set; }
}
