// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ShopEgypt.Domain.Entities;

[Table("WishlistItem")]
public partial class WishlistItem
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(450)]
    public string ApplicationUserId { get; set; }

    public int ProductId { get; set; }

    [ForeignKey("ApplicationUserId")]
    [InverseProperty("WishlistItems")]
    public virtual ApplicationUser ApplicationUser { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("WishlistItems")]
    public virtual Product Product { get; set; }
}
